#!/usr/bin/env python3
"""Ukraine-war Gate 0 hindcast (2021–2023), substitution and game off.

Same CropParams and official split as 2006–11: harvest LOWESS anomalies + AMIS,
mean flex, USA maize industrial on. FAOSTAT E0 is the 2019–21 window (latest
vendored structure). Stocks seed from 2020 PSD. p0 is 2021 Pink Sheet mean
(local numeraire; 2006–11 used 2006).

Writes diagnostics/gate0_ukraine_*.csv, figures/fig_gate0_ukraine_prices.png,
and overleaf/gate0_whitepaper/tables/ukraine_price_metrics.tex.
"""
from __future__ import annotations

import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from sheaf.dynamic_crop import result_to_monthly, run_crop_dynamics
from sheaf.data_usda import load_price_series_monthly
from score_subannual_crop import _corr, _hike

DIAG = ROOT / "diagnostics"
FIGS = ROOT / "figures"
TAB = ROOT / "overleaf" / "gate0_whitepaper" / "tables"
START, END = 2021, 2023
# 3-month mean around June 2021 vs March 2022 (invasion) / May 2022 (India wheat ban)
HIKE = (2021, 6, 2022, 5)


def _run(crop: str, **kw):
    return run_crop_dynamics(
        crop, start_year=START, end_year=END,
        stock_seed_year=2020, spin_up_years=2,
        trade_window=(2019, 2021),
        **kw,
    )


def main():
    DIAG.mkdir(parents=True, exist_ok=True)
    FIGS.mkdir(parents=True, exist_ok=True)
    TAB.mkdir(parents=True, exist_ok=True)

    pink = load_price_series_monthly(deflated=True)
    pink = pink[(pink.year >= START) & (pink.year <= END)]

    rows = []
    monthly = []
    fig, axes = plt.subplots(3, 1, figsize=(10.5, 9.2), sharex=True)
    for ax, crop in zip(axes, ("wheat", "maize", "rice")):
        p0 = float(pink[pink.year == 2021][crop].mean())
        legs = {
            "baseline": _run(crop, use_amis=False, use_shocks=False,
                             use_demand=False, use_industrial=False, p0=p0),
            "shocks": _run(crop, use_amis=False, use_shocks=True,
                           use_demand=False, p0=p0),
            "tau": _run(crop, use_amis=True, use_shocks=False,
                        use_demand=False, use_industrial=False, p0=p0),
            "full": _run(crop, use_amis=True, use_shocks=True,
                         use_demand=False, p0=p0),
        }
        obs = pink[["year", "month", crop]].rename(columns={crop: "obs_price"})
        pieces = []
        for name, res in legs.items():
            m = result_to_monthly(res)
            m["leg"] = name
            m["crop"] = crop
            pieces.append(m.merge(obs, on=["year", "month"], how="left"))
        df = pd.concat(pieces, ignore_index=True)
        monthly.append(df)
        full = df[df.leg == "full"].sort_values(["year", "month"])
        x = np.arange(len(full))
        ax.plot(x, full.obs_price, color="#c0392b", lw=2, label="Pink Sheet real 2010$")
        styles = {"full": ("-", "0.15"), "shocks": ("--", "#6c3483"),
                  "tau": ("-.", "#1e8449"), "baseline": (":", "0.5")}
        for leg, (ls, c) in styles.items():
            s = df[df.leg == leg].sort_values(["year", "month"])
            ax.plot(x, s.model_price, ls=ls, color=c, lw=1.3, label=leg)
        ax.set_ylabel("$/t")
        ax.set_title(f"{crop.capitalize()} 2021–23 (Ukraine-war window)")
        ax.legend(fontsize=7, ncol=3)
        ticks = [i for i, (y, m) in enumerate(zip(full.year, full.month)) if m == 1]
        ax.set_xticks(ticks, [str(int(full.year.iloc[i])) for i in ticks])

        y0, m0, y1, m1 = HIKE
        rec = dict(crop=crop, p0=p0)
        rec["obs_hike"] = _hike(obs, "obs_price", y0, m0, y1, m1)
        for leg in ("full", "shocks", "tau", "baseline"):
            s = df[df.leg == leg]
            rec[f"{leg}_corr"] = _corr(s.model_price, s.obs_price)
            rec[f"{leg}_hike"] = _hike(s, "model_price", y0, m0, y1, m1)
        rows.append(rec)
        print(f"{crop}: obs×{rec['obs_hike']:.2f}  full×{rec['full_hike']:.2f}  "
              f"shocks×{rec['shocks_hike']:.2f}  tau×{rec['tau_hike']:.2f}  "
              f"corr {rec['full_corr']:+.3f}")

    fig.tight_layout()
    fig_path = FIGS / "fig_gate0_ukraine_prices.png"
    fig.savefig(fig_path, dpi=140)
    plt.close(fig)

    met = pd.DataFrame(rows)
    met.to_csv(DIAG / "gate0_ukraine_score.csv", index=False)
    pd.concat(monthly, ignore_index=True).to_csv(
        DIAG / "gate0_ukraine_monthly.csv", index=False)

        lines = [
        r"% auto-generated by scripts/score_ukraine_war.py",
        r"\begin{tabular}{l rrrrr}",
        r"\toprule",
        r"Crop & obs hike & full & harvest-only & AMIS-only & full corr \\",
        r"\midrule",
    ]
    for _, r in met.iterrows():
        lines.append(
            f"{r.crop} & $\\times${r.obs_hike:.2f} & $\\times${r.full_hike:.2f} & "
            f"$\\times${r.shocks_hike:.2f} & $\\times${r.tau_hike:.2f} & "
            f"{r.full_corr:+.2f} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    (TAB / "ukraine_price_metrics.tex").write_text("\n".join(lines) + "\n")
    print(f"wrote {fig_path}")
    print(f"wrote {TAB / 'ukraine_price_metrics.tex'}")


if __name__ == "__main__":
    main()
